# Generated by Django 2.2.4 on 2022-03-30 06:45

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default=app.models.increment_invoice_number, max_length=500, null=True, verbose_name='Event Id')),
                ('customer_id', models.CharField(blank=True, default=app.models.Customer_number, max_length=500, null=True, verbose_name='Customer Id')),
                ('customer_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=2000)),
                ('amount', models.CharField(max_length=30)),
                ('place', models.TextField(max_length=2000)),
                ('status', models.CharField(max_length=30)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
    ]
