# Generated by Django 2.2.4 on 2022-03-30 14:35

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(blank=True, default=app.models.Worker_number, max_length=500, null=True, verbose_name='Worker Id')),
                ('event_id', models.CharField(max_length=200)),
                ('worker_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('tot_amount', models.CharField(max_length=200)),
                ('paid', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=2000)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
            ],
        ),
    ]
